[package]
name = "jc-motors-cotizador"
version = "0.1.4"
description = "Aplicación de escritorio para cotizaciones de JC Motors"
authors = ["JC Motors"]
edition = "2021"

[lib]
name = "jc_motors_cotizador_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
