import assert from 'node:assert/strict';
import { connect } from './cdpClient.mjs';
import { internalDemoFixtures } from './internalDemoFixtures.mjs';

const c = await connect(Number(process.env.CDP_PORT ?? 9223));
try {
  if (!process.env.TAURI_TEST) await c.send('Page.navigate', { url: 'http://127.0.0.1:5173/#/control-interno' });
  await c.waitFor('Boolean(document.querySelector("nav"))');
  const fixtures = internalDemoFixtures();
  await c.evaluate(`localStorage.setItem('jc-motors:quotations:v1', ${JSON.stringify(JSON.stringify(fixtures.quotations))}); localStorage.setItem('jc-motors-internal-costs-v1', ${JSON.stringify(JSON.stringify(fixtures.records))}); localStorage.removeItem('jc-motors:internal-controls:v1'); location.hash = '#/control-interno'; location.reload()`);
  await c.waitFor('document.querySelectorAll(".profit-table tbody tr").length === 4');
  await c.send('Emulation.setDeviceMetricsOverride', { width: 1586, height: 992, deviceScaleFactor: 1, mobile: false });
  await c.click('.profit-table tbody tr button');
  await c.waitFor('Boolean(document.querySelector(".profit-items input"))');
  await c.screenshot('tests/artifacts/control-interno-desktop.png');
  const quoteBefore = await c.evaluate('localStorage.getItem("jc-motors:quotations:v1")');
  await c.fill('.profit-search input', 'maria');
  await c.waitFor('document.querySelectorAll(".profit-table tbody tr").length === 1');
  assert.match(await c.evaluate('document.querySelector(".profit-table tbody").innerText'), /María/);
  await c.fill('.profit-search input', 'ABC-2');
  await c.waitFor('document.querySelector(".profit-table tbody").innerText.includes("Luis")');
  await c.fill('.profit-search input', '');
  await c.fill('.profit-status-filter select', 'pending');
  await c.waitFor('document.querySelectorAll(".profit-table tbody tr").length === 1');
  assert.match(await c.evaluate('document.querySelector(".profit-table tbody").innerText'), /Ana/);
  await c.fill('.profit-status-filter select', 'all');
  await c.click('.profit-segments button:first-child');
  await c.waitFor('document.querySelectorAll(".profit-table tbody tr").length === 1');
  await c.click('.profit-segments button:nth-child(2)');
  await c.waitFor('document.querySelector(".profit-segments button:nth-child(2)").getAttribute("aria-pressed") === "true"');
  await c.click('.profit-segments button:nth-child(3)');
  await c.waitFor('document.querySelectorAll(".profit-table tbody tr").length === 4');
  await c.click('.profit-range-button');
  await c.fill('.profit-range-popover label:first-child input', '2020-01-01');
  await c.fill('.profit-range-popover label:nth-child(2) input', '2020-01-31');
  await c.click('.profit-range-popover .profit-primary');
  await c.waitFor('document.body.innerText.includes("No hay cotizaciones aprobadas en este periodo")');
  assert.match(await c.evaluate('document.querySelector(".profit-metric-value").innerText'), /0\.00/);
  await c.click('.profit-segments button:nth-child(3)');
  await c.waitFor('document.querySelectorAll(".profit-table tbody tr").length === 4');
  await c.click('.profit-table tbody tr:first-child button');
  await c.waitFor('Boolean(document.querySelector(".profit-items input"))');
  await c.fill('.profit-items input', '9000.50');
  await c.waitFor('Boolean(document.querySelector(".profit-total-result .profit-negative"))');
  await c.click('.profit-detail-actions button:nth-child(2)');
  await c.waitFor('Boolean(document.querySelector("dialog[open]"))');
  await c.click('dialog[open] button:first-child');
  await c.waitFor('!document.querySelector("dialog[open]")');
  await c.click('.profit-detail-actions button[type=submit]');
  await c.waitFor('document.body.innerText.includes("Gastos guardados correctamente")');
  assert.equal(await c.evaluate('localStorage.getItem("jc-motors:quotations:v1")'), quoteBefore);
  await c.evaluate('location.reload()');
  await c.waitFor('document.querySelectorAll(".profit-table tbody tr").length === 4');
  await c.click('.profit-table tbody tr:first-child button');
  await c.waitFor('document.querySelector(".profit-items input")?.value.includes("9,000.50")');
  await c.click('.profit-add');
  await c.fill('.profit-expense-row:last-of-type input:first-child', 'Grúa');
  await c.fill('.profit-expense-row:last-of-type input:nth-child(2)', '250.10');
  await c.click('.profit-detail-actions button[type=submit]');
  await c.waitFor('JSON.parse(localStorage.getItem("jc-motors-internal-costs-v1")).find(r => r.quoteId === "demo-0").additionalExpenses.length === 2');
  await c.click('.profit-expense-row:last-of-type button');
  await c.waitFor('Boolean(document.querySelector("dialog[open]"))');
  await c.click('dialog[open] button:last-child');
  await c.click('.profit-detail-actions button[type=submit]');
  await c.waitFor('JSON.parse(localStorage.getItem("jc-motors-internal-costs-v1")).find(r => r.quoteId === "demo-0").additionalExpenses.length === 1');
  await c.fill('.profit-items input', '-20');
  await c.waitFor('Boolean(document.querySelector(".profit-error"))');
  assert.equal(await c.evaluate('document.querySelector(".profit-detail-actions button[type=submit]").disabled'), true);
  await c.fill('.profit-items input', '780');
  await c.click('.profit-detail-actions button:nth-child(2)');
  await c.waitFor('Boolean(document.querySelector("dialog[open]"))');
  await c.click('dialog[open] button:last-child');
  await c.waitFor('Boolean(document.querySelector(".profit-detail-empty"))');
  await c.click('.profit-table tbody tr:first-child button');
  await c.waitFor('Boolean(document.querySelector(".profit-items input"))');
  for (const width of [1440, 1024, 650]) {
    await c.send('Emulation.setDeviceMetricsOverride', { width, height: 900, deviceScaleFactor: 1, mobile: false });
    await new Promise(r => setTimeout(r, 200));
    assert.equal(await c.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), true, `No page overflow at ${width}`);
    await c.screenshot(`tests/artifacts/control-interno-${width}.png`);
  }
  await c.send('Emulation.setDeviceMetricsOverride', { width: 1586, height: 992, deviceScaleFactor: 1, mobile: false });
  await c.fill('.profit-items input', '780');
  await c.click('.profit-detail-actions button[type=submit]');
  await c.waitFor('!document.querySelector(".profit-unsaved")');
  await c.screenshot('tests/artifacts/control-interno-desktop.png');
  assert.deepEqual(c.errors, []);
  console.log('PASS: periods, search, status, selection, live loss, save, persistence, expenses, confirmation, validation, quote isolation and responsive layouts.');
} finally { c.close(); }
