import type { Quotation } from '../models/quotation';

const now = new Date();
const dateAt = (daysAgo: number): string => {
  const date = new Date(now);
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString();
};

export const quotationFixtures: Quotation[] = [
  {
    id: 'fixture-0012',
    folio: 'JC-0012',
    createdAt: dateAt(0),
    customer: { name: 'Sofía Rendón', phone: '55 9081 4477', email: 'sofia@example.com' },
    vehicle: { make: 'Mazda', model: 'CX-5', year: 2022, plates: 'JKL-118-A' },
    items: [
      { id: 'item-121', type: 'labor', description: 'Cambio de aceite y filtro', quantity: 1, saleUnitPrice: 890, amount: 890 },
      { id: 'item-122', type: 'part', description: 'Aceite sintético 5W-30 (4 L)', quantity: 1, saleUnitPrice: 1240, amount: 1240 },
      { id: 'item-123', type: 'part', description: 'Filtro de aceite', quantity: 1, saleUnitPrice: 280, amount: 280 },
    ],
    laborDiscountType: 'fixed',
    laborDiscountValue: 0,
    includeVat: true,
    validityDays: 15,
    publicNotes: 'Se recomienda revisar niveles de refrigerante sin costo.',
    status: 'Pendiente',
  },
  {
    id: 'fixture-0011',
    folio: 'JC-0011',
    createdAt: dateAt(2),
    customer: { name: 'Jorge Palafox', phone: '55 3321 9087' },
    vehicle: { make: 'Kia', model: 'Rio', year: 2020, plates: 'MNP-450-C' },
    items: [
      { id: 'item-111', type: 'labor', description: 'Cambio de frenos delanteros', quantity: 1, saleUnitPrice: 1450, amount: 1450 },
      { id: 'item-112', type: 'part', description: 'Balata delantera', quantity: 4, saleUnitPrice: 690, amount: 2760 },
    ],
    laborDiscountType: 'percentage',
    laborDiscountValue: 10,
    includeVat: true,
    validityDays: 15,
    publicNotes: '',
    status: 'Aprobada',
    approvedAt: dateAt(1),
  },
  {
    id: 'fixture-0010',
    folio: 'JC-0010',
    createdAt: dateAt(4),
    customer: { name: 'Fernanda Ruiz', phone: '55 7712 3390', email: 'fernanda.ruiz@example.com' },
    vehicle: { make: 'Chevrolet', model: 'Onix', year: 2021, plates: 'PQR-772-D' },
    items: [
      { id: 'item-101', type: 'part', description: 'Batería de 12 V', quantity: 1, saleUnitPrice: 2350, amount: 2350 },
      { id: 'item-102', type: 'labor', description: 'Instalación y prueba de carga', quantity: 1, saleUnitPrice: 450, amount: 450 },
    ],
    laborDiscountType: 'fixed',
    laborDiscountValue: 0,
    includeVat: false,
    validityDays: 10,
    publicNotes: 'Incluye garantía de 12 meses en la batería.',
    status: 'Pendiente',
  },
  {
    id: 'fixture-0009',
    folio: 'JC-0009',
    createdAt: dateAt(7),
    customer: { name: 'Miguel Ángel Torres', phone: '55 6620 1188' },
    vehicle: { make: 'Toyota', model: 'Hilux', year: 2019, plates: 'STU-334-E' },
    items: [
      { id: 'item-91', type: 'labor', description: 'Suspensión y alineación', quantity: 1, saleUnitPrice: 2100, amount: 2100 },
      { id: 'item-92', type: 'part', description: 'Amortiguador trasero', quantity: 2, saleUnitPrice: 3200, amount: 6400 },
      { id: 'item-93', type: 'part', description: 'Terminal de dirección', quantity: 1, saleUnitPrice: 1850, amount: 1850 },
    ],
    laborDiscountType: 'percentage',
    laborDiscountValue: 5,
    includeVat: true,
    validityDays: 20,
    publicNotes: '',
    status: 'Aprobada',
    approvedAt: dateAt(6),
  },
  {
    id: 'fixture-0008',
    folio: 'JC-0008',
    createdAt: dateAt(9),
    customer: { name: 'Paulina Estrada', phone: '55 4488 2231' },
    vehicle: { make: 'Nissan', model: 'Versa', year: 2018, plates: 'VWX-901-F' },
    items: [
      { id: 'item-81', type: 'labor', description: 'Diagnóstico computarizado', quantity: 1, saleUnitPrice: 750, amount: 750 },
      { id: 'item-82', type: 'part', description: 'Bobinas de encendido', quantity: 4, saleUnitPrice: 520, amount: 2080 },
    ],
    laborDiscountType: 'fixed',
    laborDiscountValue: 0,
    includeVat: true,
    validityDays: 15,
    publicNotes: '',
    status: 'Cancelada',
  },
  {
    id: 'fixture-0007',
    folio: 'JC-0007',
    createdAt: dateAt(11),
    customer: { name: 'Andrés Quintero', phone: '55 1199 5567', email: 'andres.q@example.com' },
    vehicle: { make: 'Jeep', model: 'Compass', year: 2022, plates: 'YZ1-455-G' },
    items: [
      { id: 'item-71', type: 'labor', description: 'Cambio de fluido de transmisión', quantity: 1, saleUnitPrice: 3200, amount: 3200 },
      { id: 'item-72', type: 'part', description: 'Filtro de transmisión', quantity: 1, saleUnitPrice: 980, amount: 980 },
      { id: 'item-73', type: 'part', description: 'Aceite de transmisión ATF', quantity: 4, saleUnitPrice: 410, amount: 1640 },
    ],
    laborDiscountType: 'percentage',
    laborDiscountValue: 12,
    includeVat: true,
    validityDays: 15,
    publicNotes: 'El cliente pidió entregar el vehículo por la mañana.',
    status: 'Aprobada',
    approvedAt: dateAt(10),
  },
  {
    id: 'fixture-0006',
    folio: 'JC-0006',
    createdAt: dateAt(15),
    customer: { name: 'Lucía Hernández', phone: '55 8830 7742' },
    vehicle: { make: 'Honda', model: 'CR-V', year: 2020, plates: 'ABC-123-A' },
    items: [
      { id: 'item-61', type: 'part', description: 'Kit de distribución', quantity: 1, saleUnitPrice: 5600, amount: 5600 },
      { id: 'item-62', type: 'labor', description: 'Cambio de correa de distribución', quantity: 1, saleUnitPrice: 4800, amount: 4800 },
      { id: 'item-63', type: 'part', description: 'Bomba de agua', quantity: 1, saleUnitPrice: 2300, amount: 2300 },
    ],
    laborDiscountType: 'fixed',
    laborDiscountValue: 500,
    includeVat: true,
    validityDays: 30,
    publicNotes: '',
    status: 'Pendiente',
  },
  {
    id: 'fixture-0005',
    folio: 'JC-0005',
    createdAt: dateAt(18),
    customer: { name: 'Ricardo Guzmán', phone: '55 2277 9911' },
    vehicle: { make: 'Toyota', model: 'Corolla', year: 2019, plates: 'DEF-220-B' },
    items: [
      { id: 'item-51', type: 'part', description: 'Pastillas de freno delanteras', quantity: 1, saleUnitPrice: 1980, amount: 1980 },
      { id: 'item-52', type: 'part', description: 'Discos delanteros', quantity: 2, saleUnitPrice: 1450, amount: 2900 },
      { id: 'item-53', type: 'labor', description: 'Cambio de frenos y rectificado', quantity: 1, saleUnitPrice: 1600, amount: 1600 },
    ],
    laborDiscountType: 'percentage',
    laborDiscountValue: 8,
    includeVat: true,
    validityDays: 15,
    publicNotes: '',
    status: 'Pendiente',
  },
  {
    id: 'fixture-0004',
    folio: 'JC-0004',
    createdAt: dateAt(22),
    customer: { name: 'Ana Torres', phone: '55 5567 3321', email: 'ana.torres@example.com' },
    vehicle: { make: 'Mazda', model: '3', year: 2021, plates: 'GHI-889-E' },
    items: [
      { id: 'item-41', type: 'labor', description: 'Mantenimiento mayor', quantity: 1, saleUnitPrice: 3400, amount: 3400 },
      { id: 'item-42', type: 'part', description: 'Filtro de aire y habitáculo', quantity: 1, saleUnitPrice: 890, amount: 890 },
    ],
    laborDiscountType: 'fixed',
    laborDiscountValue: 0,
    includeVat: true,
    validityDays: 15,
    publicNotes: '',
    status: 'Aprobada',
    approvedAt: dateAt(21),
  },
  {
    id: 'fixture-0003',
    folio: 'JC-0003',
    createdAt: dateAt(25),
    customer: { name: 'Mariana López', phone: '55 1234 5678', email: 'mariana@example.com' },
    vehicle: { make: 'Nissan', model: 'Sentra', year: 2021, plates: 'JKL-118-A' },
    items: [
      { id: 'item-31', type: 'labor', description: 'Servicio de afinación', quantity: 1, saleUnitPrice: 1850, amount: 1850 },
      { id: 'item-32', type: 'part', description: 'Filtro de aceite', quantity: 1, saleUnitPrice: 280, amount: 280 },
    ],
    laborDiscountType: 'fixed',
    laborDiscountValue: 0,
    includeVat: true,
    validityDays: 15,
    publicNotes: '',
    status: 'Pendiente',
  },
  {
    id: 'fixture-0002',
    folio: 'JC-0002',
    createdAt: dateAt(29),
    approvedAt: dateAt(28),
    customer: { name: 'Roberto García', phone: '55 8765 4321' },
    vehicle: { make: 'Honda', model: 'Civic', year: 2019, plates: 'XYZ-908-B' },
    items: [
      { id: 'item-21', type: 'part', description: 'Cambio de balatas delanteras', quantity: 1, saleUnitPrice: 2300, amount: 2300 },
      { id: 'item-22', type: 'labor', description: 'Mano de obra', quantity: 1, saleUnitPrice: 650, amount: 650 },
    ],
    laborDiscountType: 'fixed',
    laborDiscountValue: 0,
    includeVat: true,
    validityDays: 15,
    publicNotes: '',
    status: 'Aprobada',
  },
  {
    id: 'fixture-0001',
    folio: 'JC-0001',
    createdAt: dateAt(36),
    customer: { name: 'Laura Hernández', phone: '55 4444 1122', email: 'laura@example.com' },
    vehicle: { make: 'Volkswagen', model: 'Jetta', year: 2018, plates: 'LMN-456-C' },
    items: [
      { id: 'item-11', type: 'labor', description: 'Diagnóstico de suspensión', quantity: 1, saleUnitPrice: 850, amount: 850 },
      { id: 'item-12', type: 'part', description: 'Amortiguador delantero', quantity: 2, saleUnitPrice: 1950, amount: 3900 },
    ],
    laborDiscountType: 'fixed',
    laborDiscountValue: 0,
    includeVat: false,
    validityDays: 15,
    publicNotes: '',
    status: 'Cancelada',
  },
];